### Import PyTorch and NumPy ###

In [1]:
import torch
import numpy as np

### Create a Function to Describe a Tensor ###

In [2]:
def DescribeTensor(x):
    print("Type: {}".format(x.type()))
    print("Shape/Size: {}".format(x.shape))
    print("Values: \n{}".format(x))

### Create a Tensor ###

In [3]:
DescribeTensor(torch.Tensor(2, 3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### Create a Randomly Initialized Tensor ###

In [4]:
#Uniform Random
DescribeTensor(torch.rand(2, 3))
#Random Normal
DescribeTensor(torch.randn(2, 3))

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0.0980, 0.5265, 0.2137],
        [0.6881, 0.0618, 0.4529]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[-1.4385,  0.1243, -0.1665],
        [ 0.6474, -0.2894, -1.4550]])


### Create a Filled Tensor ###

In [5]:
DescribeTensor(torch.zeros(2, 3))

x = torch.ones(2,3)
DescribeTensor(x)

x.fill_(2)
DescribeTensor(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[2., 2., 2.],
        [2., 2., 2.]])


### Create a Tensor from Lists ###

In [6]:
x = torch.Tensor([[1, 2, 3], [4, 5, 6]])
DescribeTensor(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Create and Import a Tensor from NumPy ###

In [7]:
numpy = np.random.rand(2, 3)
DescribeTensor(torch.from_numpy(numpy))

Type: torch.DoubleTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0.7684, 0.8074, 0.3564],
        [0.4631, 0.5207, 0.4846]], dtype=torch.float64)


### Tensor - Properties ###

In [8]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
DescribeTensor(x)

x = x.long()
DescribeTensor(x)

x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int64)
DescribeTensor(x)

x = x.float()
DescribeTensor(x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])
Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Tensor - Operations - Addition ###

In [9]:
x = torch.randn(2, 3)
DescribeTensor(x)

DescribeTensor(torch.add(x, x))

DescribeTensor(x + x)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[-1.2644, -1.0998, -0.6851],
        [-0.5155, -0.5558, -0.8312]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[-2.5288, -2.1996, -1.3702],
        [-1.0310, -1.1116, -1.6624]])
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[-2.5288, -2.1996, -1.3702],
        [-1.0310, -1.1116, -1.6624]])


### Tensor - Operations - Dimensioned-Based ###

In [10]:
x = torch.arange(6)
DescribeTensor(x)

x = x.view(2, 3)
DescribeTensor(x)

DescribeTensor(torch.sum(x, dim=0))

DescribeTensor(torch.sum(x, dim=1))

DescribeTensor(torch.transpose(x, 0, 1))

Type: torch.LongTensor
Shape/Size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])
Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/Size: torch.Size([3])
Values: 
tensor([3, 5, 7])
Type: torch.LongTensor
Shape/Size: torch.Size([2])
Values: 
tensor([ 3, 12])
Type: torch.LongTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


### Slice and Index a Tensor ###

In [11]:
x = torch.arange(6).view(2, 3)
DescribeTensor(x)

DescribeTensor(x[:1, :2])

DescribeTensor(x[0, 1])

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/Size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])
Type: torch.LongTensor
Shape/Size: torch.Size([])
Values: 
1


### Noncontiguous Index of a Tensor ###

In [12]:
x = torch.arange(6).view(2, 3)
DescribeTensor(x)

indices = torch.LongTensor([0, 2])
DescribeTensor(torch.index_select(x, dim=1, index=indices))

indices = torch.LongTensor([0, 1])
DescribeTensor(torch.index_select(x, dim=0, index=indices))

row_indices = torch.arange(2).long()
column_indices = torch.LongTensor([0, 1])
DescribeTensor(x[row_indices, column_indices])

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])
Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/Size: torch.Size([2])
Values: 
tensor([0, 4])


### Concatenate Tensors ###

In [13]:
x = torch.arange(6).view(2, 3)
DescribeTensor(x)

DescribeTensor(torch.cat([x, x], dim=0))

DescribeTensor(torch.cat([x, x], dim=1))

DescribeTensor(torch.stack([x, x]))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/Size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/Size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])
Type: torch.LongTensor
Shape/Size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


### Linear Algebra on Tensors - Multiplication ###

In [14]:
x1 = torch.arange(6).view(2, 3)
DescribeTensor(x1)

x2 = torch.ones((3, 2), dtype=torch.int64)
x2[:, 1] += 1
DescribeTensor(x2)

DescribeTensor(torch.mm(x1, x2))

Type: torch.LongTensor
Shape/Size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])
Type: torch.LongTensor
Shape/Size: torch.Size([3, 2])
Values: 
tensor([[1, 2],
        [1, 2],
        [1, 2]])
Type: torch.LongTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[ 3,  6],
        [12, 24]])


### Create Tensor for Gradient Bookkeeping ###

In [15]:
x = torch.ones(2, 2, requires_grad=True)
DescribeTensor(x)
print(x.grad is None)

y = (x + 2) * (x + 5) + 3
DescribeTensor(y)
print(x.grad is None)

z = y.mean()
DescribeTensor(z)
z.backward()
print(x.grad is None)

Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True
Type: torch.FloatTensor
Shape/Size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True
Type: torch.FloatTensor
Shape/Size: torch.Size([])
Values: 
21.0
False
